[project]
name = "robocute"
version = "0.1.0"
description = "Make Robotics Cute!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rbc_meta",
    "nanobind-stubgen>=0.1.5",
    "requests"
]

[project.scripts]
prepare = "scripts.main:prepare"
gen = "scripts.main:generate"


[tool.uv.sources]
rbc_meta = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
